client.println("HTTP/1.1 200 OK\nContent-type:text/html\n\n<!DOCTYPE html><html><head>");
client.println("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">");
client.println("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>");
client.println("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>");
client.println("</head><body style=\"background-color: #4b2e83; color: #b7a57a;\"><nav class=\"navbar navbar-inverse\"><div class=\"container-fluid\">");
client.println("<div class=\"navbar-header\"><p class=\"navbar-brand\">Team Optimistic</p></div><ul class=\"nav navbar-nav\">");
client.print("<li class=\"active\"><a href=\"/H\">Refresh Data</a></li><li class=\"dropdown\"><a class=\"dropdown-toggle\"");
client.println("data-toggle=\"dropdown\" href=\"#\">Communication<span class=\"caret\"></span></a><ul class=\"dropdown-menu\">");
client.print("<li><a>Master to Slave: ");
client.print("5");
client.println("</a></li><li><a>Slave to Master: ");
client.print("4");
client.print("</a></li><li><a>Master to Terminal: ");
client.print("4");
client.println("</a></li><li><a>Terminal to Master: ");
client.print("4");
client.println("</a></li></ul></li></ul></div></nav>");                       
client.println("<div class=\"container-fluid text-center\">");
client.println("<div class=\"jumbotron jumbotron-fluid\" style=\"background-color:#85754d;color:#fff;\"><h1>Smart Doorbell Dashboard</h1></div>");
client.print("<div class =\"row\"><div class=\"col-sm-4\"><h2 class=\"alert alert-warning\">");
client.print("70");
client.println("&#8457;</h2><h2>Temperature</h2></div>");						
client.println("<div class=\"col-sm-4\"><h2 class=\"alert alert-warning\">");
client.print("80");
client.print("%</h2><h2>Humidity</h2></div>");
client.print("<div class=\"col-sm-4\"><h2 class=\"alert alert-warning\">");
client.print("Wet");
client.println("</h2><h2>Rain</h2></div></div>");
client.print("<div class=\"row\"><div class=\"col-sm-4\"><h2 class=\"alert alert-warning\">");
client.print("1");
client.print("ppm</h2><h2>Smoke</h2></div>");               
client.print("<div class=\"col-sm-4\"><h2 class=\"alert alert-warning\">");
client.print("0.3"); 
client.println("mg/m<sup>3</sup></h2><h2>Dust</h2></div>");
client.print("<div class=\"col-sm-4\"><h2 class=\"alert alert-warning\">");
client.print("Bright");
client.println("</h2><h2>Light</h2></div></div>");
client.println("<div class =\"row\"><div class=\"col-sm-4\"><h2 class=\"alert alert-warning\">");
client.print("5");
client.println("ppm</h2><h2>CO</h2></div>");		
client.println("<div class=\"col-sm-4\"><h2 class=\"alert alert-warning\">");
client.print("500");
client.println("ppm</h2><h2>CO2</h2></div><div class=\"col-sm-4\">");
client.println("<h2 class=\"alert alert-warning\">");
client.print("1");
client.println("ppm</h2><h2>LPG</h2></div></div><hr style=\"border-top: 1px solid #85754d;\">");
client.println("<p>&copy;2017 Copyright: Pouria &amp; Conard</p><div></body></html>");